# Homework 2

In [120]:
import pandas as pd

We start by reading data from a csv-file and add a new column with the prices per square meters for each apartment.

In [122]:
df = pd.read_csv("Booli_sold.csv")

In [123]:
df["ppsqm"] = df["soldPrice"] / df["livingArea"]
df

,listPrice,rent,livingArea,rooms,published,constructionYear,objectType,booliId,soldDate,soldPrice,...,location.position.longitude,location.position.isApproximate,location.region.municipalityName,location.region.countyName,location.distance.ocean,source.name,source.id,source.type,source.url,ppsqm
0,3995000,4467.0,73.0,3.0,2018-10-15 13:33:18,1935.0,Lägenhet,3263989,2018-11-08,3820000,...,18.054057,NaN,Stockholm,Stockholms län,260,MOHV,1901865,Broker,http://www.mohv.se/,52328.767123
1,1995000,1773.0,36.0,1.0,2018-10-05 14:29:28,1968.0,Lägenhet,3256231,2018-10-19,2355000,...,18.057821,NaN,Stockholm,Stockholms län,218,Notar,1566,Broker,http://www.notar.se/,65416.666667
2,5100000,3839.0,81.0,3.0,2018-09-11 13:44:43,1936.0,Lägenhet,3236660,2018-09-27,6110000,...,18.054716,NaN,Stockholm,Stockholms län,186,Historiska Hem AB,65645750,Broker,http://historiskahem.se/,75432.098765
3,5495000,4483.0,107.0,4.0,2018-08-25 02:56:56,1936.0,Lägenhet,3224374,2018-09-06,8050000,...,18.053880,NaN,Stockholm,Stockholms län,218,Notar,1566,Broker,http://www.notar.se/,75233.644860
4,1995000,1696.0,29.0,1.0,2018-06-15 17:16:19,1936.0,Lägenhet,3185496,2018-06-18,2400000,...,18.053542,True,Stockholm,Stockholms län,166,Mäklarhuset,204,Broker,http://www.maklarhuset.se/,82758.620690
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,1495000,1388.0,26.0,1.0,2012-10-20 07:36:37,1935.0,Lägenhet,1297784,2012-11-30,1475000,...,18.055659,True,Stockholm,Stockholms län,101,Notar,1566,Broker,http://www.notar.se/,56730.769231
154,2245000,2455.0,50.0,2.0,2012-10-19 15:32:58,1935.0,Lägenhet,1296874,2012-10-27,2245000,...,18.055659,True,Stockholm,Stockholms län,101,Notar,1566,Broker,http://www.notar.se/,44900.000000
155,1450000,1072.0,23.0,1.0,2012-09-14 05:10:08,1936.0,Lägenhet,1270599,2012-10-22,1450000,...,18.053552,NaN,Stockholm,Stockholms län,255,Notar,1566,Broker,http://www.notar.se/,63043.478261
156,2495000,2748.0,56.0,3.0,2012-09-21 12:19:37,1935.0,Lägenhet,1276232,2012-10-09,2200000,...,18.054634,True,Stockholm,Stockholms län,70,Notar,1566,Broker,http://www.notar.se/,39285.714286
157,2300000,2455.0,50.0,2.0,2012-09-16 02:33:35,1935.0,Lägenhet,1272477,2012-10-09,2180000,...,18.055659,True,Stockholm,Stockholms län,101,Notar,1566,Broker,http://www.notar.se/,43600.000000

Here we create a new sorted table with the 5 apartments having the highest price per square meters.

In [125]:
df_top5_ppsqm = df.sort_values("ppsqm", ascending=False).head(5)
df_top5_ppsqm

,listPrice,rent,livingArea,rooms,published,constructionYear,objectType,booliId,soldDate,soldPrice,...,location.position.longitude,location.position.isApproximate,location.region.municipalityName,location.region.countyName,location.distance.ocean,source.name,source.id,source.type,source.url,ppsqm
67,1595000,1464.0,24.0,1.0,2016-01-07 14:51:06,1935.0,Lägenhet,2018259,2016-01-21,2500000,...,18.055270,NaN,Stockholm,Stockholms län,161,Notar,1566,Broker,http://www.notar.se/,104166.666667
50,1890000,1464.0,24.0,1.0,2016-06-11 08:55:51,1935.0,Lägenhet,2125576,2016-06-21,2450000,...,18.055270,NaN,Stockholm,Stockholms län,161,HusmanHagberg,1610,Broker,http://www.husmanhagberg.se/,102083.333333
54,1795000,1374.0,23.0,1.0,2016-04-15 19:10:49,1935.0,Lägenhet,2078171,2016-04-28,2300000,...,18.055422,True,Stockholm,Stockholms län,135,Notar,1566,Broker,http://www.notar.se/,100000.000000
34,1750000,1144.0,25.0,1.0,2017-05-18 16:20:57,1936.0,Lägenhet,2330886,2017-06-01,2210000,...,18.053880,NaN,Stockholm,Stockholms län,218,HusmanHagberg,1610,Broker,http://www.husmanhagberg.se/,88400.000000
55,1895000,1522.0,26.9,1.0,2016-04-01 22:56:37,1968.0,Lägenhet,2067384,2016-04-19,2300000,...,18.058529,True,Stockholm,Stockholms län,298,Notar,1566,Broker,http://www.notar.se/,85501.858736

Now we calculate the average price per square meters for all the 158 apartments.

In [127]:
avg_ppsqm = df["ppsqm"].sum() / len(df["ppsqm"])
avg_ppsqm

58387.48793248627

If we look again at the price per square meters but expand the table to the top 20 apartments and then sort by oldest we can see that no apartment sold before 2015-07-02 makes the list.

In [129]:
df_top20_ppsqm = df.sort_values("ppsqm", ascending=False).head(20)
df_top20_ppsqm.sort_values("soldDate")

,listPrice,rent,livingArea,rooms,published,constructionYear,objectType,booliId,soldDate,soldPrice,...,location.position.longitude,location.position.isApproximate,location.region.municipalityName,location.region.countyName,location.distance.ocean,source.name,source.id,source.type,source.url,ppsqm
89,1950000,1865.0,31.0,2.0,2015-06-18 11:26:53,NaN,Lägenhet,1908856,2015-07-02,2300000,...,18.053552,NaN,Stockholm,Stockholms län,255,Notar,1566,Broker,http://www.notar.se/,74193.548387
86,2150000,2164.0,32.0,2.0,2015-08-11 13:09:47,1939.0,Lägenhet,1930664,2015-08-26,2730000,...,18.055422,True,Stockholm,Stockholms län,135,Svensk Fastighetsförmedling,713,Broker,http://www.svenskfast.se/,85312.500000
85,1995000,1885.0,36.0,1.0,2015-08-14 14:04:38,1968.0,Lägenhet,1933262,2015-09-07,2610000,...,18.058368,True,Stockholm,Stockholms län,246,Notar,1566,Broker,http://www.notar.se/,72500.000000
67,1595000,1464.0,24.0,1.0,2016-01-07 14:51:06,1935.0,Lägenhet,2018259,2016-01-21,2500000,...,18.055270,NaN,Stockholm,Stockholms län,161,Notar,1566,Broker,http://www.notar.se/,104166.666667
65,3995000,4089.0,73.5,3.0,2015-12-29 14:37:41,1935.0,Lägenhet,2013074,2016-01-25,5400000,...,18.054052,True,Stockholm,Stockholms län,164,Notar,1566,Broker,http://www.notar.se/,73469.387755
55,1895000,1522.0,26.9,1.0,2016-04-01 22:56:37,1968.0,Lägenhet,2067384,2016-04-19,2300000,...,18.058529,True,Stockholm,Stockholms län,298,Notar,1566,Broker,http://www.notar.se/,85501.858736
54,1795000,1374.0,23.0,1.0,2016-04-15 19:10:49,1935.0,Lägenhet,2078171,2016-04-28,2300000,...,18.055422,True,Stockholm,Stockholms län,135,Notar,1566,Broker,http://www.notar.se/,100000.000000
51,2495000,2394.0,38.0,2.0,2016-04-22 09:13:43,1935.0,Lägenhet,2082909,2016-05-17,3150000,...,18.054052,True,Stockholm,Stockholms län,164,Notar,1566,Broker,http://www.notar.se/,82894.736842
50,1890000,1464.0,24.0,1.0,2016-06-11 08:55:51,1935.0,Lägenhet,2125576,2016-06-21,2450000,...,18.055270,NaN,Stockholm,Stockholms län,161,HusmanHagberg,1610,Broker,http://www.husmanhagberg.se/,102083.333333
41,2250000,2488.0,39.0,2.0,2017-04-14 15:24:32,1937.0,Lägenhet,2302822,2017-04-28,2810000,...,18.055092,True,Stockholm,Stockholms län,186,SkandiaMäklarna,1570,Broker,http://www.skandiamaklarna.se/,72051.282051
36,3975000,2452.0,57.0,2.0,2017-05-03 17:17:48,1935.0,Lägenhet,2314649,2017-05-22,4210000,...,18.055084,True,Stockholm,Stockholms län,68,Karlsson & Uddare,1619,Broker,http://www.karlssonuddare.se/,73859.649123
34,1750000,1144.0,25.0,1.0,2017-05-18 16:20:57,1936.0,Lägenhet,2330886,2017-06-01,2210000,...,18.053880,NaN,Stockholm,Stockholms län,218,HusmanHagberg,1610,Broker,http://www.husmanhagberg.se/,88400.000000
32,5995000,4990.0,97.0,4.0,2017-06-25 13:40:05,1935.0,Lägenhet,2359557,2017-07-08,7500000,...,18.054986,True,Stockholm,Stockholms län,136,Notar,1566,Broker,http://www.notar.se/,77319.587629
29,2595000,2232.0,37.0,1.0,2017-07-28 13:02:18,1939.0,Lägenhet,2374010,2017-09-01,2715000,...,18.055270,NaN,Stockholm,Stockholms län,161,Svensk Fastighetsförmedling,713,Broker,http://www.svenskfast.se/,73378.378378
24,2500000,1400.0,35.0,1.0,2017-09-08 15:22:24,1936.0,Lägenhet,2405043,2017-10-06,2560000,...,18.053880,NaN,Stockholm,Stockholms län,218,HusmanHagberg,1610,Broker,http://www.husmanhagberg.se/,73142.857143
19,1995000,1880.0,31.0,2.0,2017-11-18 16:56:07,1936.0,Lägenhet,3045712,2017-12-05,2450000,...,18.053552,NaN,Stockholm,Stockholms län,255,Notar,1566,Broker,http://www.notar.se/,79032.258065
10,2295000,1743.0,29.0,1.0,2018-05-05 04:43:36,1935.0,Lägenhet,3125674,2018-05-19,2420000,...,18.054986,True,Stockholm,Stockholms län,136,Mäklarhuset,204,Broker,http://www.maklarhuset.se/,83448.275862
4,1995000,1696.0,29.0,1.0,2018-06-15 17:16:19,1936.0,Lägenhet,3185496,2018-06-18,2400000,...,18.053542,True,Stockholm,Stockholms län,166,Mäklarhuset,204,Broker,http://www.maklarhuset.se/,82758.620690
3,5495000,4483.0,107.0,4.0,2018-08-25 02:56:56,1936.0,Lägenhet,3224374,2018-09-06,8050000,...,18.053880,NaN,Stockholm,Stockholms län,218,Notar,1566,Broker,http://www.notar.se/,75233.644860
2,5100000,3839.0,81.0,3.0,2018-09-11 13:44:43,1936.0,Lägenhet,3236660,2018-09-27,6110000,...,18.054716,NaN,Stockholm,Stockholms län,186,Historiska Hem AB,65645750,Broker,http://historiskahem.se/,75432.098765

From the dataframe *df* which is sorted by most recently sold we can see that the apartment sold 2015-07-02 is on place 90. Therefore none of the 68 oldest apartments makes the top 20. This shows a clear trend of increasing prices.